language: php

php:
  - '7.0'

before_install:
  - sudo apt-get update > /dev/null

before_script:
  - composer install -n
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
